import React from 'react';
import { Link } from 'react-router-dom';
import { Brain, Target, TrendingUp, Users, CheckCircle, ArrowRight } from 'lucide-react';
import Header from '../components/Header';

interface HomeProps {
  user: any;
  onLogout: () => void;
}

const Home: React.FC<HomeProps> = ({ user, onLogout }) => {
  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Questions',
      description: 'Get personalized interview questions generated by advanced AI based on your role and experience level.'
    },
    {
      icon: Target,
      title: 'Realistic Simulations',
      description: 'Practice with lifelike interview scenarios that mirror real-world interview experiences.'
    },
    {
      icon: TrendingUp,
      title: 'Performance Analytics',
      description: 'Track your progress with detailed feedback and analytics to identify areas for improvement.'
    },
    {
      icon: Users,
      title: 'Multiple Interview Types',
      description: 'Practice technical, behavioral, and case study interviews across various industries.'
    }
  ];

  const benefits = [
    'Boost confidence with unlimited practice sessions',
    'Receive instant AI-powered feedback',
    'Track progress over time',
    'Practice anytime, anywhere'
  ];

  return (
    <div className="min-h-screen bg-slate-50">
      <Header user={user} onLogout={onLogout} />
      
      <main>
        {/* Hero Section */}
        <section className="bg-gradient-to-br from-blue-600 via-blue-700 to-indigo-800 text-white">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
            <div className="flex flex-col items-center text-center gap-12">
              <div className="max-w-2xl">
                <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold leading-tight mb-6">
                  Master Your Next
                  <span className="block">Interview</span>
                </h1>
                <p className="text-xl text-blue-100 mb-8 leading-relaxed">
                  Practice with AI-powered interview simulations, get personalized feedback,
                  and build the confidence you need to land your dream job.
                </p>
                <div className="flex flex-col sm:flex-row gap-4 justify-center">
                  {user ? (
                    <Link
                      to="/dashboard"
                      className="inline-flex items-center justify-center px-8 py-4 bg-white text-blue-600 font-semibold hover:bg-blue-50 transition-colors"
                    >
                      Go to Dashboard
                      <ArrowRight className="ml-2 w-5 h-5" />
                    </Link>
                  ) : (
                    <>
                      <Link
                        to="/register"
                        className="inline-flex items-center justify-center px-8 py-4 bg-white text-blue-600 font-semibold hover:bg-blue-50 transition-colors"
                      >
                        Sign up
                        <ArrowRight className="ml-2 w-5 h-5" />
                      </Link>
                      <Link
                        to="/login"
                        className="inline-flex items-center justify-center px-8 py-4 border-2 border-white text-white font-semibold hover:bg-white hover:text-blue-600 transition-colors"
                      >
                        Login
                      </Link>
                    </>
                  )}
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section className="py-20">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">
                Benefits of AI Interview Prep
              </h2>
              <p className="text-xl text-slate-600 max-w-3xl mx-auto">
                We use cutting-edge AI technology and proven interview techniques 
                to give you a competitive edge in all kinds of tech interviews.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
              {features.map((feature, index) => (
                <div key={index} className="bg-white p-6 shadow-sm border border-slate-200 hover:shadow-md transition-shadow">
                  <div className="w-12 h-12 bg-blue-100 flex items-center justify-center mb-4">
                    <feature.icon className="w-6 h-6 text-blue-600" />
                  </div>
                  <h3 className="text-lg font-semibold text-slate-900 mb-2">{feature.title}</h3>
                  <p className="text-slate-600">{feature.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Benefits Section */}
        <section className="py-20 bg-white">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="max-w-3xl mx-auto text-center">
              <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-6">
                Transform Your Interview Performance
              </h2>
              <p className="text-lg text-slate-600 mb-8">
                Join thousands of professionals who have landed highly competitive
                jobs by using our AI-powered interview preparation platform.
              </p>
              <ul className="space-y-4 mx-auto max-w-md text-left">
                {benefits.map((benefit, index) => (
                  <li key={index} className="flex items-center space-x-3">
                    <CheckCircle className="w-5 h-5 text-green-500 flex-shrink-0" />
                    <span className="text-slate-700">{benefit}</span>
                  </li>
                ))}
              </ul>
              {!user && (
                <div className="mt-8">
                  <Link
                    to="/register"
                    className="inline-flex items-center px-6 py-3 bg-blue-600 text-white font-semibold hover:bg-blue-700 transition-colors"
                  >
                    Get Started Today
                    <ArrowRight className="ml-2 w-4 h-4" />
                  </Link>
                </div>
              )}
            </div>
          </div>
        </section>

        {/* CTA Section */}
        {!user && (
          <section className="py-20 bg-slate-900 text-white">
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
              <h2 className="text-3xl md:text-4xl font-bold mb-4">
                Ready to Ace Your Next Interview?
              </h2>
              <p className="text-xl text-slate-300 mb-8">
                Start practicing today with our AI-powered interview simulator!
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Link
                  to="/register"
                  className="inline-flex items-center justify-center px-8 py-4 bg-blue-600 text-white font-semibold hover:bg-blue-700 transition-colors"
                >
                  Sign up
                  <ArrowRight className="ml-2 w-5 h-5" />
                </Link>
                <Link
                  to="/login"
                  className="inline-flex items-center justify-center px-8 py-4 border-2 border-slate-600 text-slate-300 font-semibold hover:bg-slate-800 hover:border-slate-500 transition-colors"
                >
                  Login
                </Link>
              </div>
            </div>
          </section>
        )}
      </main>
    </div>
  );
};

export default Home;
